[package]
name = "ratfist-server"
version = "0.1.0"
authors = ["Ondrej Palenicek <ondrej.palenicek@gmail.com>"]

[dependencies]
rocket = "0.2"
rocket_codegen = "0.2"
rocket_contrib = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
log = "0.3"
serial = "0.3"


[features]
spinner = []
